### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'size'

### ISSUE THREAD

**Issue by surfertas** [thnkim/OpenFacePytorch#3]
I see that f is a tuple, consisting of (x, x_736), the result of the forward() method in the netOpenFace class. I am getting AttributeError: 'tuple' object has no attribute 'size' when I run your code as is. 

Is this expected?

The following code is from the last few lines in loadOpenFace.py.
```    
for i in range(f.size(0) - 1):
        for j in range(i + 1, f.size(0)):
            df = f[i] - f[j]
            print(img_paths[i].split('/')[-1], img_paths[j].split('/')[-1], torch.dot(df, df))
```

**Comment by yoniker** [comment]
I'm having the exact same issue. Rather, I can see that the author has tried to compute the L2 of the difference of each 2 images, but  in fact f is a tuple, where f[0] is a Tensor of the size num_imagesx128 and f[1] is of the size num_imagesx736 and I am not quite sure which of those I should use!

Actually I've tried now both options, and even though I've cropped and aligned the faces, none of those L2 losses makes any sense :P

**Comment by thnkim** [comment]
Oh, sorry for the very belated response. I was off.
x will be an 128d embedding or x_736. The original was just x, but I added x_736 without update of the main function. Sorry again :)

And regardless of the main function in loadOpenFace.py, 
1) you may want to try Cosine distance for 128d feature.
2) for 736d feature, I'm not sure which metric is the best because it is the intermediate output of the network. I guess L2 would work.
